# Generated by Django 3.1.7 on 2022-01-03 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211231_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('m3u8', models.TextField(blank=True, null=True)),
                ('done', models.BooleanField(default=False)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.channel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
