# Generated by Django 3.1.7 on 2022-01-04 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_linkchannel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkchannel',
            name='channel',
        ),
        migrations.AddField(
            model_name='channel',
            name='link_m3u8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.linkchannel'),
        ),
    ]
