# Generated by Django 3.1.7 on 2022-01-12 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20220112_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='link_m3u8',
            field=models.TextField(blank=True, null=True),
        ),
    ]
