# Generated by Django 3.1.7 on 2022-01-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20220128_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='custom_m3u8',
            field=models.TextField(blank=True, null=True),
        ),
    ]
