# Generated by Django 3.1.7 on 2022-02-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_channel_custom_m3u8'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
