# Generated by Django 3.1.7 on 2022-02-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_episodio_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='program_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
