# Generated by Django 3.1.7 on 2022-02-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_programday_programitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programitem',
            name='start',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='programitem',
            name='stop',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
