#! /usr/bin/python
# -*- coding: UTF-8 -*-
"""
Global variables for base module
"""
from django.conf import LazySettings
from django.utils.translation import ugettext_lazy as _

settings = LazySettings()


def get_from_settings_or_default(var_name, default):
    try:
        return settings.__getattr__(var_name)
    except AttributeError:
        return default


# Items by page on paginator views
ITEMS_BY_PAGE = 10

CREATE_SUFFIX = "_create"
LIST_SUFFIX = "_list"
DETAIL_SUFFIX = "_detail"
UPDATE_SUFFIX = "_update"
DELETE_SUFFIX = "_delete"

API_SUFFIX = "_api"
style = "base_django/flexbox"

# Messages
OBJECT_CREATED_SUCCESSFULLY = _("Object created successfully")
OBJECT_UPDATED_SUCCESSFULLY = _("Object updated successfully")
OBJECT_DELETED_SUCCESSFULLY = _("Object deleted successfully")

BASE_MODELS_TRANSLATION_NAME = _("Name")
BASE_MODELS_TRANSLATION_DESCRIPTION = _("Description")
BASE_MODELS_TRANSLATION_SLUG = _("Slug")
BASE_MODELS_TRANSLATION_CREATED = _("Created")
BASE_MODELS_TRANSLATION_MODIFIED = _("Modified")
BASE_MODELS_TRANSLATION_ACTIVE = _("Active")

CONFIGURING_APPLICATION = _("Configuring application {}")
CREATING_PERMISSION_WITH_NAME = _("Creating Permission with name {}")
CREATING_GROUP_WITH_NAME = _("Creating Group with name {}")

MOVIE_PREFIX = "MOVIE"

MOVIE_VERBOSE_NAME = _("Movie")
MOVIE_VERBOSE_NAME_PLURAL = _("Movie")

MOVIE_LIST_URL_NAME = MOVIE_PREFIX + LIST_SUFFIX
MOVIE_CREATE_URL_NAME = MOVIE_PREFIX + CREATE_SUFFIX
MOVIE_DETAIL_URL_NAME = MOVIE_PREFIX + DETAIL_SUFFIX
MOVIE_UPDATE_URL_NAME = MOVIE_PREFIX + UPDATE_SUFFIX
MOVIE_DELETE_URL_NAME = MOVIE_PREFIX + DELETE_SUFFIX
MOVIE_LIST_JSON_URL_NAME = MOVIE_PREFIX + '_list_json'

SERIE_PREFIX = "SERIE"

SERIE_VERBOSE_NAME = _("Serie")
SERIE_VERBOSE_NAME_PLURAL = _("Serie")

SERIE_LIST_URL_NAME = SERIE_PREFIX + LIST_SUFFIX
SERIE_CREATE_URL_NAME = SERIE_PREFIX + CREATE_SUFFIX
SERIE_DETAIL_URL_NAME = SERIE_PREFIX + DETAIL_SUFFIX
SERIE_UPDATE_URL_NAME = SERIE_PREFIX + UPDATE_SUFFIX
SERIE_DELETE_URL_NAME = SERIE_PREFIX + DELETE_SUFFIX
SERIE_LIST_JSON_URL_NAME = SERIE_PREFIX + '_list_json'

CHANNEL_PREFIX = "CHANNEL"

CHANNEL_VERBOSE_NAME = _("Channel")
CHANNEL_VERBOSE_NAME_PLURAL = _("Channel")

CHANNEL_LIST_URL_NAME = CHANNEL_PREFIX + LIST_SUFFIX
CHANNEL_CREATE_URL_NAME = CHANNEL_PREFIX + CREATE_SUFFIX
CHANNEL_DETAIL_URL_NAME = CHANNEL_PREFIX + DETAIL_SUFFIX
CHANNEL_UPDATE_URL_NAME = CHANNEL_PREFIX + UPDATE_SUFFIX
CHANNEL_DELETE_URL_NAME = CHANNEL_PREFIX + DELETE_SUFFIX
CHANNEL_LIST_JSON_URL_NAME = CHANNEL_PREFIX + '_list_json'
