# Generated by Selenium IDE
import time

from app.tests.base import BaseSeleniumTestCase
from app.views.channel import get_m3u8_channels
from app.views.megapack import MegaPack


class TestFinal(BaseSeleniumTestCase):

    def test_final(self):
        mega = MegaPack()
        print('---- Starting: ')
        print(time.asctime())
        get_m3u8_channels({}, mega)
        print(time.asctime())
        print('---- Finish CRON JOB: ')
        mega.close()
